'use strict';

window.d3 = require('d3');
window.ndarray = require('ndarray');
window.qrComplex = require('ndarray-householder-qr-complex');
window.pack = require('ndarray-pack');
window.unpack = require('ndarray-unpack');
window.show = require('ndarray-show');
window.pool = require('ndarray-scratch');
window.cwise = require('cwise');
window.ops = require('ndarray-ops');
window.cops = require('ndarray-complex');
window.fill = require('ndarray-fill');
window.linspace = require('ndarray-linspace');
window.controlPanel = require('control-panel');
window.PID = require('node-pid-controller');
window.katex = require('katex');
window.autoRenderKatex = require('katex/dist/contrib/auto-render.min');
window.regl = require('regl');
window.normals = require('angle-normals');
window.bunny = require('bunny');
window.extend = require('util-extend');

window.Animation = require('./util/animation');
window.Plotter = require('./util/plotter');
window.Timer = require('./util/timer');
window.scatter = require('./util/scatter');
window.createCamera = require('./util/camera');
window.transfiniteInterpolation = require('./util/transfinite-interpolation');
window.vectorFill = require('./util/vector-fill');
